package com.mod.trading.service;

import com.ib.client.Contract;
import com.ib.client.Decimal;
import com.ib.client.EClientSocket;
import com.ib.client.Order;
import com.mod.trading.config.TradeWebSocketHandler;
import com.mod.trading.entity.TradeOrder;
import com.mod.trading.entity.User;
import com.mod.trading.exception.InvalidTradeRequestException;
import com.mod.trading.exception.TradingDisabledException;
import com.mod.trading.exception.UserNotFoundException;
import com.mod.trading.ibkr.IbkrConnectionManager;
import com.mod.trading.ibkr.IbkrEventWrapper;
import com.mod.trading.ibkr.IbkrException;
import com.mod.trading.model.TradeRequest;
import com.mod.trading.repository.TradeOrderRepository;
import com.mod.trading.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.slf4j.MDC;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDate;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Trading service backed by Interactive Brokers TWS API.
 *
 * Differences from the previous Alpaca implementation:
 *   - Orders are placed asynchronously via IB Gateway socket.
 *   - Bracket orders are submitted as 3 linked orders (parent + take-profit + stop-loss).
 *   - orderId is allocated by IBKR (not generated by us).
 *   - We block on a CompletableFuture to surface a synchronous result for the controller.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class IbkrService {

    private final TradeOrderRepository orderRepository;
    private final UserRepository userRepository;
    private final IbkrConnectionManager connectionManager;
    private final IbkrEventWrapper eventWrapper;
    private final TradeWebSocketHandler webSocketHandler;

    /** Sequence used as reqId for non-order requests (account summary, etc.) */
    private final AtomicInteger reqIdSequence = new AtomicInteger(9000);

    private static final BigDecimal HUNDRED = new BigDecimal("100");
    private static final BigDecimal TWO = new BigDecimal("2");
    private static final long ORDER_ACK_TIMEOUT_SECONDS = 15;

    @Transactional
    public TradeOrder placeOrder(TradeRequest request, String username) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));

        MDC.put("userId", String.valueOf(user.getId()));
        MDC.put("symbol", request.getSymbol());
        try {
            return doPlaceOrder(request, user);
        } finally {
            MDC.clear();
        }
    }

    private TradeOrder doPlaceOrder(TradeRequest request, User user) {
        if (!connectionManager.isConnected() || !eventWrapper.isReady()) {
            throw new IbkrException(-1, "IB Gateway not connected. Try again in a few seconds.");
        }
        if (!user.isTradingEnabled()) {
            throw new TradingDisabledException("Trading disabled for this account");
        }

        // Daily loss limit
        if (user.getDailyLossLimit() != null && user.getDailyLossLimit().signum() > 0) {
            BigDecimal todayLossPotential = orderRepository.sumPotentialLossesToday(
                    user.getId(), LocalDate.now().atStartOfDay());
            if (todayLossPotential.compareTo(user.getDailyLossLimit()) >= 0) {
                throw new TradingDisabledException(
                        "Daily loss limit reached: " + todayLossPotential + "/" + user.getDailyLossLimit());
            }
        }

        // Inputs
        String symbol = request.getSymbol().toUpperCase();
        BigDecimal entryPrice = request.getEntryPrice();
        BigDecimal stopLoss = request.getStopLoss();
        BigDecimal tradeAmount = user.getTradeAmount();
        BigDecimal range = user.getRangeValue();
        BigDecimal profitPct = user.getProfitPercent();

        // Validation
        if (stopLoss.compareTo(entryPrice) >= 0) {
            throw new InvalidTradeRequestException(
                    "Stop loss (" + stopLoss + ") must be below entry price (" + entryPrice + ")");
        }
        int qty = tradeAmount.divide(entryPrice, 0, RoundingMode.DOWN).intValue();
        if (qty <= 0) {
            throw new InvalidTradeRequestException(
                    "Trade amount " + tradeAmount + " insufficient for " + symbol + " at " + entryPrice);
        }

        // Computed prices (matches the previous Alpaca behaviour)
        BigDecimal stopPrice = entryPrice.add(range).setScale(2, RoundingMode.HALF_UP);
        BigDecimal limitPrice = entryPrice.add(range.multiply(TWO)).setScale(2, RoundingMode.HALF_UP);
        BigDecimal takeProfit = entryPrice
                .multiply(BigDecimal.ONE.add(profitPct.divide(HUNDRED, 8, RoundingMode.HALF_UP)))
                .setScale(2, RoundingMode.HALF_UP);

        if (takeProfit.compareTo(stopLoss) <= 0) {
            throw new InvalidTradeRequestException(
                    "Take profit (" + takeProfit + ") must be above stop loss (" + stopLoss + ")");
        }

        log.info("Placing IBKR bracket: symbol={} qty={} stopPrice={} limitPrice={} tp={} sl={}",
                symbol, qty, stopPrice, limitPrice, takeProfit, stopLoss);

        // Build the bracket: parent STP LMT + child LMT (take-profit) + child STP (stop-loss).
        Contract contract = stockContract(symbol);

        int parentId = eventWrapper.allocateOrderId();
        int takeProfitId = eventWrapper.allocateOrderId();
        int stopLossId = eventWrapper.allocateOrderId();

        Order parent = stopLimitOrder("BUY", qty, stopPrice, limitPrice, parentId);
        parent.transmit(false); // hold; we transmit only when the last child is sent

        Order tpOrder = limitOrder("SELL", qty, takeProfit, takeProfitId, parentId);
        tpOrder.transmit(false);

        Order slOrder = stopOrder("SELL", qty, stopLoss, stopLossId, parentId);
        slOrder.transmit(true); // last child triggers transmission of all three

        // Idempotency / correlation key for our own DB
        String clientOrderId = "TB-" + UUID.randomUUID();

        // Register the future BEFORE placing - avoids missing fast callbacks
        var ackFuture = eventWrapper.registerPendingOrder(parentId);

        EClientSocket client = connectionManager.getClient();
        client.placeOrder(parentId, contract, parent);
        client.placeOrder(takeProfitId, contract, tpOrder);
        client.placeOrder(stopLossId, contract, slOrder);

        // Wait for IBKR to acknowledge the parent
        IbkrEventWrapper.OrderAck ack;
        try {
            ack = ackFuture.get(ORDER_ACK_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        } catch (java.util.concurrent.TimeoutException te) {
            log.error("IBKR did not acknowledge order {} within {}s", parentId, ORDER_ACK_TIMEOUT_SECONDS);
            throw new IbkrException(-1, "Order acknowledgement timeout");
        } catch (java.util.concurrent.ExecutionException ee) {
            // Unwrap IbkrException thrown by error() callback
            if (ee.getCause() instanceof IbkrException ibe) throw ibe;
            throw new IbkrException(-1, ee.getCause() == null ? "Unknown" : ee.getCause().getMessage());
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            throw new IbkrException(-1, "Interrupted while waiting for order ack");
        }

        TradeOrder order = new TradeOrder();
        order.setUser(user);
        order.setClientOrderId(clientOrderId);
        order.setSymbol(symbol);
        order.setQty(qty);
        order.setEntryPrice(entryPrice);
        order.setTradeAmount(tradeAmount);
        order.setProfitPercent(profitPct);
        order.setStopPrice(stopPrice);
        order.setLimitPrice(limitPrice);
        order.setTakeProfit(takeProfit);
        order.setStopLoss(stopLoss);
        order.setIbkrParentOrderId(parentId);
        order.setIbkrTakeProfitOrderId(takeProfitId);
        order.setIbkrStopLossOrderId(stopLossId);
        order.setIbkrPermId(ack.permId());
        order.setOrderStatus(ack.status());

        TradeOrder saved = orderRepository.save(order);

        webSocketHandler.sendToUser(user.getUsername(), "ORDER_PLACED", Map.of(
                "id", saved.getId(),
                "symbol", saved.getSymbol(),
                "qty", saved.getQty(),
                "parentOrderId", saved.getIbkrParentOrderId(),
                "status", saved.getOrderStatus()
        ));

        return saved;
    }

    /**
     * Cancel an open order (kill switch for a single position).
     */
    public void cancelOrder(Long tradeOrderId, String username) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));

        TradeOrder order = orderRepository.findById(tradeOrderId)
                .filter(o -> o.getUser().getId().equals(user.getId()))
                .orElseThrow(() -> new InvalidTradeRequestException("Order not found"));

        if (!connectionManager.isConnected()) {
            throw new IbkrException(-1, "IB Gateway not connected");
        }

        log.info("Cancelling IBKR order parentId={}", order.getIbkrParentOrderId());
        // OrderCancel is the modern API; fall back to legacy if your TWS API jar is older.
        connectionManager.getClient().cancelOrder(order.getIbkrParentOrderId(), "");
    }

    public Map<String, String> getAccountSummary(String username) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));
        if (!connectionManager.isConnected()) {
            throw new IbkrException(-1, "IB Gateway not connected");
        }
        if (user.getIbkrAccountId() == null || user.getIbkrAccountId().isBlank()) {
            throw new InvalidTradeRequestException(
                    "User has no IBKR account configured. Set ibkrAccountId in profile.");
        }

        int reqId = reqIdSequence.incrementAndGet();
        var future = eventWrapper.registerAccountSummary(reqId);

        connectionManager.getClient().reqAccountSummary(reqId, "All",
                "NetLiquidation,TotalCashValue,BuyingPower,GrossPositionValue,AvailableFunds");

        try {
            Map<String, String> data = future.get(15, TimeUnit.SECONDS);
            connectionManager.getClient().cancelAccountSummary(reqId);
            return data;
        } catch (java.util.concurrent.TimeoutException te) {
            connectionManager.getClient().cancelAccountSummary(reqId);
            throw new IbkrException(-1, "Account summary timeout");
        } catch (java.util.concurrent.ExecutionException | InterruptedException e) {
            if (e instanceof InterruptedException) Thread.currentThread().interrupt();
            throw new IbkrException(-1, e.getMessage());
        }
    }

    public List<TradeOrder> getOrders(String username, Pageable pageable) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));
        return orderRepository.findByUserIdOrderByCreatedAtDesc(user.getId(), pageable).getContent();
    }

    public List<TradeOrder> getOrdersBySymbol(String username, String symbol, Pageable pageable) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));
        return orderRepository.findByUserIdAndSymbolOrderByCreatedAtDesc(
                user.getId(), symbol.toUpperCase(), pageable).getContent();
    }

    public List<TradeOrder> getLastOrders(String username) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));
        return orderRepository.findTop10ByUserIdOrderByCreatedAtDesc(user.getId());
    }

    public Map<String, Object> getSettings(String username) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));
        Map<String, Object> settings = new HashMap<>();
        settings.put("tradeAmount", user.getTradeAmount());
        settings.put("rangeValue", user.getRangeValue());
        settings.put("profitPercent", user.getProfitPercent());
        settings.put("dailyLossLimit", user.getDailyLossLimit());
        settings.put("tradingEnabled", user.isTradingEnabled());
        settings.put("ibkrAccountId", user.getIbkrAccountId());
        return settings;
    }

    @Transactional
    public User updateSettings(String username, BigDecimal tradeAmount, BigDecimal rangeValue,
                               BigDecimal profitPercent, BigDecimal dailyLossLimit) {
        User user = userRepository.findByUsername(username)
                .orElseThrow(() -> new UserNotFoundException(username));
        user.setTradeAmount(tradeAmount);
        user.setRangeValue(rangeValue);
        user.setProfitPercent(profitPercent);
        if (dailyLossLimit != null) user.setDailyLossLimit(dailyLossLimit);
        return userRepository.save(user);
    }

    public boolean isConnected() {
        return connectionManager.isConnected() && eventWrapper.isReady();
    }

    // ============================================================
    // Helpers to build TWS API objects
    // ============================================================

    private Contract stockContract(String symbol) {
        Contract c = new Contract();
        c.symbol(symbol);
        c.secType("STK");
        c.exchange("SMART");      // IBKR's Smart Routing
        c.primaryExch("NASDAQ");  // Helps disambiguate dual-listed symbols
        c.currency("USD");
        return c;
    }

    private Order stopLimitOrder(String action, int qty, BigDecimal stopPrice,
                                  BigDecimal limitPrice, int orderId) {
        Order o = new Order();
        o.orderId(orderId);
        o.action(action);
        o.orderType("STP LMT");
        o.totalQuantity(Decimal.parse(String.valueOf(qty)));
        o.lmtPrice(limitPrice.doubleValue());
        o.auxPrice(stopPrice.doubleValue()); // stop trigger
        o.tif("GTC");
        o.outsideRth(false);
        return o;
    }

    private Order limitOrder(String action, int qty, BigDecimal limitPrice,
                              int orderId, int parentId) {
        Order o = new Order();
        o.orderId(orderId);
        o.parentId(parentId);
        o.action(action);
        o.orderType("LMT");
        o.totalQuantity(Decimal.parse(String.valueOf(qty)));
        o.lmtPrice(limitPrice.doubleValue());
        o.tif("GTC");
        return o;
    }

    private Order stopOrder(String action, int qty, BigDecimal stopPrice,
                             int orderId, int parentId) {
        Order o = new Order();
        o.orderId(orderId);
        o.parentId(parentId);
        o.action(action);
        o.orderType("STP");
        o.totalQuantity(Decimal.parse(String.valueOf(qty)));
        o.auxPrice(stopPrice.doubleValue());
        o.tif("GTC");
        return o;
    }
}
